import type { UiProduct } from './types';

/**
 * Initial product catalog used as a fallback when Supabase isn't configured
 * (i.e. demo / preview mode). Real products come from the database.
 */
export const SEED_PRODUCTS: UiProduct[] = [
  {
    id: 'seed-1',
    name: 'Clare Clarity Facewash',
    cat: 'Facewash',
    sub: 'Daily Cleanse · Face',
    price: 'PKR 1,850',
    pricePkr: 1850,
    desc: 'Gentle amino acid-based cleanser preserving the skin barrier while deeply purifying pores.',
    badge: null,
    image: null,
    inStock: true,
    isFeatured: true,
    displayOrder: 1,
  },
  {
    id: 'seed-2',
    name: 'Vix Active Serum',
    cat: 'Serum',
    sub: 'Active Treatment · Face',
    price: 'PKR 3,200',
    pricePkr: 3200,
    desc: 'Niacinamide, Hyaluronic Acid & Vitamin C blend targeting hyperpigmentation, texture & glow.',
    badge: 'Bestseller',
    image: null,
    inStock: true,
    isFeatured: true,
    displayOrder: 2,
  },
  {
    id: 'seed-3',
    name: 'Clare-Barrier Moisturizer',
    cat: 'Moisturizer',
    sub: 'Hydration · Face',
    price: 'PKR 2,400',
    pricePkr: 2400,
    desc: 'Ceramide-rich daily moisturizer rebuilding the skin barrier and locking in lasting hydration.',
    badge: null,
    image: null,
    inStock: true,
    isFeatured: true,
    displayOrder: 3,
  },
  {
    id: 'seed-4',
    name: 'SPF 50 Veil Sunscreen',
    cat: 'Sunscreen',
    sub: 'Sun Protection · Face',
    price: 'PKR 2,750',
    pricePkr: 2750,
    desc: 'Weightless mineral sunscreen. Broad spectrum UVA/UVB protection for daily use.',
    badge: 'SPF 50',
    image: null,
    inStock: true,
    isFeatured: true,
    displayOrder: 4,
  },
  {
    id: 'seed-5',
    name: 'Deep Glow Mask',
    cat: 'Mask',
    sub: 'Weekly Treatment · Face',
    price: 'PKR 1,950',
    pricePkr: 1950,
    desc: 'Kaolin clay & niacinamide mask that purifies pores, controls shine, and restores clarity.',
    badge: 'New',
    image: null,
    inStock: true,
    isFeatured: false,
    displayOrder: 5,
  },
  {
    id: 'seed-6',
    name: 'Brightening Vitamin C Serum',
    cat: 'Serum',
    sub: 'Brightening · Face',
    price: 'PKR 2,900',
    pricePkr: 2900,
    desc: 'High-potency 15% stabilised Vitamin C with ferulic acid for luminous, even skin tone.',
    badge: null,
    image: null,
    inStock: true,
    isFeatured: false,
    displayOrder: 6,
  },
  {
    id: 'seed-7',
    name: 'Radiance Renewal Mask',
    cat: 'Mask',
    sub: 'Glow Treatment · Face',
    price: 'PKR 2,100',
    pricePkr: 2100,
    desc: 'Enzyme exfoliating mask with papaya extract and AHA complex for smooth, radiant skin.',
    badge: 'New',
    image: null,
    inStock: true,
    isFeatured: false,
    displayOrder: 7,
  },
  {
    id: 'seed-8',
    name: 'Hydra-Plump Moisturizer',
    cat: 'Moisturizer',
    sub: 'Intensive Hydration · Face',
    price: 'PKR 2,650',
    pricePkr: 2650,
    desc: 'Triple hyaluronic acid formula for dehydrated skin. 72-hour moisture lock technology.',
    badge: null,
    image: null,
    inStock: true,
    isFeatured: false,
    displayOrder: 8,
  },
  {
    id: 'seed-9',
    name: 'Gentle Rice Facewash',
    cat: 'Facewash',
    sub: 'Brightening Cleanse · Face',
    price: 'PKR 1,650',
    pricePkr: 1650,
    desc: 'Fermented rice water and PHA for gentle brightening and a velvety-clean finish.',
    badge: null,
    image: null,
    inStock: true,
    isFeatured: false,
    displayOrder: 9,
  },
  {
    id: 'seed-10',
    name: 'Scalp Renewal Shampoo',
    cat: 'Shampoo',
    sub: 'Strengthen · Hair',
    price: 'PKR 1,600',
    pricePkr: 1600,
    desc: 'Biotin and keratin-enriched shampoo for strengthened, voluminous hair from root to tip.',
    badge: null,
    image: null,
    inStock: true,
    isFeatured: false,
    displayOrder: 10,
  },
  {
    id: 'seed-11',
    name: 'Nourish Hair Oil',
    cat: 'Oil',
    sub: 'Deep Nourishment · Hair',
    price: 'PKR 1,950',
    pricePkr: 1950,
    desc: 'Cold-pressed argan, jojoba, and rosemary oil for deep nourishment and scalp health.',
    badge: null,
    image: null,
    inStock: true,
    isFeatured: false,
    displayOrder: 11,
  },
  {
    id: 'seed-12',
    name: 'Vix Hair Tonic',
    cat: 'Tonic',
    sub: 'Growth Stimulant · Hair',
    price: 'PKR 2,100',
    pricePkr: 2100,
    desc: 'Caffeine and peptide-activated scalp tonic that stimulates follicles and reduces hair fall.',
    badge: 'Bestseller',
    image: null,
    inStock: true,
    isFeatured: false,
    displayOrder: 12,
  },
  {
    id: 'seed-13',
    name: 'Balance Scalp Shampoo',
    cat: 'Shampoo',
    sub: 'Oil Control · Hair',
    price: 'PKR 1,700',
    pricePkr: 1700,
    desc: 'Zinc PCA and salicylic acid shampoo for oily, dandruff-prone scalps.',
    badge: null,
    image: null,
    inStock: true,
    isFeatured: false,
    displayOrder: 13,
  },
];
